use std::fmt::Write as _;

use atom_ffi::AtomResult;
use atom_manifest::{AndroidConfig, AppConfig, BuildConfig, metadata_target};
use atom_modules::ResolvedModule;
use camino::{Utf8Path, Utf8PathBuf};

use crate::PlatformPlan;

pub(crate) fn build_android_plan(
    app: &AppConfig,
    build: &BuildConfig,
    android: &AndroidConfig,
) -> PlatformPlan {
    let generated_root = build.generated_root.join("android").join(&app.slug);
    let package_dir = kotlin_package_dir(
        android
            .application_id
            .as_deref()
            .expect("android application id should be present when enabled"),
    );
    let source_root = generated_root.join("src/main/kotlin").join(package_dir);
    let files = vec![
        generated_root.join("BUILD.bazel"),
        generated_root.join("AndroidManifest.generated.xml"),
        source_root.join("AtomApplication.kt"),
        source_root.join("AtomBindings.kt"),
        source_root.join("MainActivity.kt"),
    ];
    PlatformPlan {
        target: format!("//{}:app", generated_root.as_str()),
        generated_root,
        files,
    }
}

pub(crate) fn render_android_build_file(
    app: &AppConfig,
    modules: &[ResolvedModule],
    android: &AndroidConfig,
) -> AtomResult<String> {
    let package_name = android.application_id.as_deref().unwrap_or_default();
    let package_dir = kotlin_package_dir(package_name);
    let jni_prefix = jni_prefix(package_name);
    let source_root = Utf8PathBuf::from("src/main/kotlin").join(package_dir);
    let mut contents = String::from(
        "# Generated by atom. Do not edit.\n\
load(\"@rules_android//android:rules.bzl\", \"android_binary\")\n\
load(\"@rules_rust//rust:defs.bzl\", \"rust_shared_library\")\n\
load(\"@rules_kotlin//kotlin:jvm.bzl\", \"kt_jvm_library\")\n\n",
    );
    contents.push_str("rust_shared_library(\n");
    contents.push_str("    name = \"atom_runtime_jni\",\n");
    contents.push_str("    srcs = [\"//templates/atom_runtime_jni:lib.rs\"],\n");
    contents.push_str("    crate_name = \"atom_runtime_jni\",\n");
    contents.push_str("    edition = \"2024\",\n");
    contents.push_str("    rustc_env = {\n");
    let _ = writeln!(
        contents,
        "        \"ATOM_JNI_INIT_EXPORT\": \"{jni_prefix}_initRuntime\","
    );
    let _ = writeln!(
        contents,
        "        \"ATOM_JNI_LIFECYCLE_EXPORT\": \"{jni_prefix}_handleLifecycle\","
    );
    let _ = writeln!(
        contents,
        "        \"ATOM_JNI_SHUTDOWN_EXPORT\": \"{jni_prefix}_shutdown\","
    );
    contents.push_str("    },\n");
    contents.push_str("    visibility = [\"//visibility:private\"],\n");
    contents.push_str("    deps = [\n");
    contents.push_str("        \"//crates/atom-ffi\",\n");
    contents.push_str("        \"//crates/atom-runtime\",\n");
    let _ = writeln!(contents, "        \"{}\",", app.entry_crate_label);
    contents.push_str("    ],\n");
    contents.push_str(")\n\n");
    contents.push_str("kt_jvm_library(\n");
    contents.push_str("    name = \"generated_kotlin\",\n");
    contents.push_str("    srcs = [\n");
    let _ = writeln!(
        contents,
        "        \"{}/AtomApplication.kt\",",
        source_root.as_str()
    );
    let _ = writeln!(
        contents,
        "        \"{}/AtomBindings.kt\",",
        source_root.as_str()
    );
    let _ = writeln!(
        contents,
        "        \"{}/MainActivity.kt\",",
        source_root.as_str()
    );
    for module in modules {
        let label = metadata_target(&module.request.target_label, "_android_srcs")?;
        let _ = writeln!(contents, "        \"{label}\",");
    }
    contents.push_str("    ],\n");
    contents.push_str("    visibility = [\"//visibility:public\"],\n");
    contents.push_str(")\n\n");
    contents.push_str("android_binary(\n");
    contents.push_str("    name = \"app\",\n");
    contents.push_str("    manifest = \"AndroidManifest.generated.xml\",\n");
    let _ = writeln!(contents, "    custom_package = \"{package_name}\",");
    contents.push_str("    deps = [\":generated_kotlin\"],\n");
    contents.push_str("    data = [\":atom_runtime_jni\"],\n");
    contents.push_str("    visibility = [\"//visibility:public\"],\n");
    contents.push_str(")\n");
    Ok(contents)
}

pub(crate) fn render_android_manifest_xml(app: &AppConfig, android: &AndroidConfig) -> String {
    format!(
        r#"<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="{}">
  <uses-sdk android:minSdkVersion="{}" android:targetSdkVersion="{}" />
  <application android:label="{}" android:name=".AtomApplication">
    <activity android:name=".MainActivity" android:exported="true" />
  </application>
</manifest>
"#,
        android.application_id.as_deref().unwrap_or_default(),
        android.min_sdk.unwrap_or_default(),
        android.target_sdk.unwrap_or_default(),
        app.name
    )
}

pub(crate) fn render_kotlin_application(app: &AppConfig, android: &AndroidConfig) -> String {
    let package_name = android.application_id.as_deref().unwrap_or_default();
    format!(
        "package {package_name}\n\nclass AtomApplication {{\n    val name: String = \"{name}\"\n    val slug: String = \"{slug}\"\n}}\n",
        name = app.name,
        slug = app.slug
    )
}

pub(crate) fn render_kotlin_bindings(
    modules: &[ResolvedModule],
    android: &AndroidConfig,
) -> String {
    let package_name = android.application_id.as_deref().unwrap_or_default();
    let mut contents =
        format!("package {package_name}\n\nobject AtomBindings {{\n    val modules = listOf(\n");
    for module in modules {
        let _ = writeln!(contents, "        \"{}\",", module.manifest.id);
    }
    contents.push_str("    )\n\n    val moduleSummary: String\n        get() = modules.joinToString(separator = \", \")\n}\n");
    contents
}

pub(crate) fn render_kotlin_main_activity(
    app: &AppConfig,
    generated_root: &Utf8Path,
    android: &AndroidConfig,
) -> String {
    let package_name = android.application_id.as_deref().unwrap_or_default();
    format!(
        "package {package_name}\n\nimport java.nio.file.Files\nimport java.nio.file.Paths\n\nclass MainActivity {{\n    fun run() {{\n        val application = AtomApplication()\n        val handle = AtomRuntimeBridge.initRuntime()\n        check(handle != 0L) {{ \"atom_app_init failed\" }}\n        try {{\n            println(\"Booting {name} ({slug}) on Android\")\n            println(\"Modules: ${{AtomBindings.moduleSummary}}\")\n            check(AtomRuntimeBridge.handleLifecycle(handle, 2) == 0) {{ \"background transition failed\" }}\n            check(AtomRuntimeBridge.handleLifecycle(handle, 3) == 0) {{ \"suspend transition failed\" }}\n            check(AtomRuntimeBridge.handleLifecycle(handle, 4) == 0) {{ \"resume transition failed\" }}\n            check(AtomRuntimeBridge.handleLifecycle(handle, 5) == 0) {{ \"terminate transition failed\" }}\n            println(\"Started ${{application.name}} with slug ${{application.slug}}\")\n        }} finally {{\n            AtomRuntimeBridge.shutdown(handle)\n        }}\n    }}\n}}\n\nprivate object AtomRuntimeBridge {{\n    init {{\n        System.load(resolveLibraryPath())\n    }}\n\n    external fun initRuntime(): Long\n    external fun handleLifecycle(handle: Long, event: Int): Int\n    external fun shutdown(handle: Long)\n\n    private fun resolveLibraryPath(): String {{\n        val runfilesDir = System.getenv(\"JAVA_RUNFILES\")\n            ?: System.getenv(\"RUNFILES_DIR\")\n            ?: error(\"Bazel runfiles directory is not available\")\n        val libraryName = System.mapLibraryName(\"atom_runtime_jni\")\n        val candidates = listOf(\"_main\", \"atom\").map {{ workspace ->\n            Paths.get(runfilesDir, workspace, \"{generated_root}\", libraryName)\n        }}\n        return candidates.firstOrNull(Files::exists)?.toString()\n            ?: error(\"Unable to locate atom_runtime_jni in Bazel runfiles\")\n    }}\n}}\n\nfun main() {{\n    MainActivity().run()\n}}\n",
        name = app.name,
        slug = app.slug,
        generated_root = generated_root.as_str()
    )
}

pub(crate) fn kotlin_package_dir(application_id: &str) -> Utf8PathBuf {
    Utf8PathBuf::from(application_id.replace('.', "/"))
}

fn jni_prefix(application_id: &str) -> String {
    format!(
        "Java_{}_AtomRuntimeBridge",
        jni_mangle_segment(application_id)
    )
}

fn jni_mangle_segment(value: &str) -> String {
    let mut mangled = String::new();
    for character in value.chars() {
        match character {
            '.' => mangled.push('_'),
            '_' => mangled.push_str("_1"),
            '$' => mangled.push_str("_00024"),
            value if value.is_ascii_alphanumeric() => mangled.push(value),
            _ => mangled.push('_'),
        }
    }
    mangled
}
