use std::fmt::Write as _;
use std::fs;

use atom_ffi::{AtomError, AtomErrorCode, AtomResult};
use atom_modules::{ModuleKind, ResolvedModule};
use camino::{Utf8Path, Utf8PathBuf};

use crate::rust_source::{parse_rust_module, render_flatbuffer_schema};

const FLATBUFFERS_JAVA_RUNTIME_SRCS: &[&str] = &[
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/ArrayReadWriteBuf.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/BaseVector.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/BooleanVector.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/ByteBufferReadWriteBuf.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/ByteBufferUtil.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/ByteVector.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/Constants.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/DoubleVector.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/FlatBufferBuilder.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/FlexBuffers.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/FlexBuffersBuilder.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/FloatVector.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/IntVector.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/LongVector.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/ReadBuf.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/ReadWriteBuf.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/ShortVector.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/StringVector.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/Struct.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/Table.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/UnionVector.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/Utf8.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/Utf8Old.java",
    "@flatbuffers//:java/src/main/java/com/google/flatbuffers/Utf8Safe.java",
];

const FLATBUFFERS_SWIFT_RUNTIME_SRCS: &[&str] = &[
    "@flatbuffers//swift:Sources/Common/Int+extension.swift",
    "@flatbuffers//swift:Sources/Common/Scalar.swift",
    "@flatbuffers//swift:Sources/Common/padding.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/ByteBuffer.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/Constants.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/Enum.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/FlatBufferBuilder.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/FlatBufferObject.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/FlatBuffersUtils.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/FlatbuffersErrors.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/Message.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/Mutable.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/NativeObject.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/Offset.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/Root.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/String+extension.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/Struct.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/Table.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/TableVerifier.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/VeriferOptions.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/Verifiable.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/Verifier.swift",
    "@flatbuffers//swift:Sources/FlatBuffers/_InternalByteBuffer.swift",
];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ModuleFlatbufferPackage {
    pub module_id: String,
    pub package_root: Utf8PathBuf,
    pub build_file: Utf8PathBuf,
    pub rust_wrapper: Utf8PathBuf,
    pub generated_schema: Option<GeneratedSchemaFile>,
    pub source_schemas: Vec<SchemaSource>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedSchemaFile {
    pub path: Utf8PathBuf,
    pub contents: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SchemaSource {
    pub label: String,
    pub stem: String,
    pub kotlin_out: Utf8PathBuf,
}

impl ModuleFlatbufferPackage {
    #[must_use]
    pub fn build_contents(&self) -> String {
        let target_prefix = self.module_id.replace('-', "_");
        let rust_rule_name = format!("{target_prefix}_rust_flatbuffers_srcs");
        let swift_rule_name = format!("{target_prefix}_swift_flatbuffers_srcs");
        let kotlin_rule_name = format!("{target_prefix}_kotlin_flatbuffers_srcs");
        let rust_outs = flatbuffer_outputs(&self.source_schemas, "rs");
        let swift_outs = flatbuffer_outputs(&self.source_schemas, "swift");
        let mut output = String::from(
            "# Generated by atom. Do not edit.\n\
load(\"@build_bazel_rules_swift//swift:swift.bzl\", \"swift_library\")\n\
load(\"@flatbuffers//:build_defs.bzl\", \"flatbuffer_library_public\")\n\
load(\"@rules_java//java:defs.bzl\", \"java_library\")\n\
load(\"@rules_kotlin//kotlin:jvm.bzl\", \"kt_jvm_library\")\n\
load(\"@rules_rust//rust:defs.bzl\", \"rust_library\")\n\n\
package(default_visibility = [\"//visibility:public\"])\n\n",
        );

        render_flatbuffer_rule(
            &mut output,
            &rust_rule_name,
            &self.source_schemas,
            &rust_outs,
            "--rust",
            &[],
        );
        output.push('\n');
        render_rust_library(&mut output, &target_prefix, &rust_rule_name);
        output.push('\n');

        render_flatbuffer_rule(
            &mut output,
            &swift_rule_name,
            &self.source_schemas,
            &swift_outs,
            "--swift",
            &[],
        );
        output.push('\n');
        render_swift_library(&mut output, &target_prefix, &swift_rule_name);
        output.push('\n');

        render_kotlin_flatbuffer_genrules(&mut output, &kotlin_rule_name, &self.source_schemas);
        output.push('\n');
        render_java_runtime_library(&mut output);
        output.push('\n');
        render_kotlin_library(&mut output, &target_prefix, &kotlin_rule_name);
        output
    }

    #[must_use]
    pub fn rust_wrapper_contents(&self) -> String {
        let mut output = String::from("// Generated by atom. Do not edit.\n");
        for schema in &self.source_schemas {
            writeln!(output, "pub mod {}_generated;", schema.stem)
                .expect("writing to String should not fail");
            writeln!(output, "pub use self::{}_generated::*;", schema.stem)
                .expect("writing to String should not fail");
        }
        output
    }
}

/// # Errors
///
/// Returns an error if the module's generated schema/build package cannot be
/// planned from the available metadata and source inputs.
pub fn plan_module_flatbuffers(
    repo_root: &Utf8Path,
    module: &ResolvedModule,
) -> AtomResult<ModuleFlatbufferPackage> {
    let package_root = module
        .manifest
        .generated_root
        .join("flatbuffers")
        .join(&module.manifest.id);
    let build_file = package_root.join("BUILD.bazel");
    let rust_wrapper = package_root.join("lib.rs");

    match module.manifest.kind {
        ModuleKind::Rust => {
            let crate_root = module.manifest.crate_root.as_ref().ok_or_else(|| {
                AtomError::with_path(
                    AtomErrorCode::CngTemplateError,
                    "rust module metadata must include crate_root",
                    module.metadata_path.as_str(),
                )
            })?;
            let parsed = parse_rust_module(repo_root, crate_root)?;
            if parsed.is_empty() {
                return Err(AtomError::with_path(
                    AtomErrorCode::CngTemplateError,
                    "rust module must declare at least one #[atom_record], #[atom_export], or #[atom_import] item",
                    crate_root.as_str(),
                ));
            }
            let schema_name = module.manifest.id.replace('-', "_");
            let schema_path = package_root.join(format!("{schema_name}.fbs"));
            let schema_contents = render_flatbuffer_schema(&module.manifest.id, &parsed)?;
            Ok(ModuleFlatbufferPackage {
                module_id: module.manifest.id.clone(),
                package_root,
                build_file,
                rust_wrapper,
                generated_schema: Some(GeneratedSchemaFile {
                    path: schema_path,
                    contents: schema_contents,
                }),
                source_schemas: vec![SchemaSource {
                    label: format!("{schema_name}.fbs"),
                    stem: schema_name.clone(),
                    kotlin_out: kotlin_onefile_output(
                        &["atom".to_owned(), module.manifest.id.replace('-', "_")],
                        &schema_name,
                    ),
                }],
            })
        }
        ModuleKind::Native => {
            let source_schemas = module
                .manifest
                .schema_files
                .iter()
                .map(|schema_path| plan_native_schema_source(repo_root, module, schema_path))
                .collect::<AtomResult<Vec<_>>>()?;
            Ok(ModuleFlatbufferPackage {
                module_id: module.manifest.id.clone(),
                package_root,
                build_file,
                rust_wrapper,
                generated_schema: None,
                source_schemas,
            })
        }
    }
}

fn plan_native_schema_source(
    repo_root: &Utf8Path,
    module: &ResolvedModule,
    schema_path: &Utf8Path,
) -> AtomResult<SchemaSource> {
    let namespace = parse_flatbuffer_namespace(&repo_root.join(schema_path))?;
    let label = bazel_file_label(&module.manifest.target_label, schema_path)?;
    let stem = schema_path
        .file_stem()
        .ok_or_else(|| {
            AtomError::with_path(
                AtomErrorCode::CngTemplateError,
                "native module schema file must have a file stem",
                schema_path.as_str(),
            )
        })?
        .replace('-', "_");

    Ok(SchemaSource {
        label,
        stem: stem.clone(),
        kotlin_out: kotlin_onefile_output(&namespace, &stem),
    })
}

fn render_flatbuffer_rule(
    output: &mut String,
    name: &str,
    sources: &[SchemaSource],
    outs: &[String],
    language_flag: &str,
    flatc_args: &[&str],
) {
    writeln!(output, "flatbuffer_library_public(").expect("writing to String should not fail");
    writeln!(output, "    name = \"{name}\",").expect("writing to String should not fail");
    writeln!(output, "    srcs = [").expect("writing to String should not fail");
    for source in sources {
        writeln!(output, "        \"{}\",", source.label)
            .expect("writing to String should not fail");
    }
    writeln!(output, "    ],").expect("writing to String should not fail");
    writeln!(output, "    outs = [").expect("writing to String should not fail");
    for out in outs {
        writeln!(output, "        \"{out}\",").expect("writing to String should not fail");
    }
    writeln!(output, "    ],").expect("writing to String should not fail");
    writeln!(output, "    language_flag = \"{language_flag}\",")
        .expect("writing to String should not fail");
    if !flatc_args.is_empty() {
        writeln!(output, "    flatc_args = [").expect("writing to String should not fail");
        for arg in flatc_args {
            writeln!(output, "        \"{arg}\",").expect("writing to String should not fail");
        }
        writeln!(output, "    ],").expect("writing to String should not fail");
    }
    writeln!(output, ")").expect("writing to String should not fail");
}

fn render_kotlin_flatbuffer_genrules(output: &mut String, name: &str, sources: &[SchemaSource]) {
    let mut generated_labels = Vec::with_capacity(sources.len());
    for schema in sources {
        let genrule_name = format!("{}_kotlin", schema.stem);
        writeln!(output, "genrule(").expect("writing to String should not fail");
        writeln!(output, "    name = \"{genrule_name}\",")
            .expect("writing to String should not fail");
        writeln!(output, "    srcs = [").expect("writing to String should not fail");
        writeln!(output, "        \"{}\",", schema.label)
            .expect("writing to String should not fail");
        writeln!(output, "    ],").expect("writing to String should not fail");
        writeln!(output, "    outs = [").expect("writing to String should not fail");
        writeln!(output, "        \"{}\",", schema.kotlin_out)
            .expect("writing to String should not fail");
        writeln!(output, "    ],").expect("writing to String should not fail");
        writeln!(output, "    tools = [\"@flatbuffers//:flatc\"],")
            .expect("writing to String should not fail");
        writeln!(
            output,
            "    cmd = \"src=$(location {}); src_dir=$$(dirname $$src); $(location @flatbuffers//:flatc) --gen-object-api --gen-compare --no-includes --gen-mutable --reflect-names --kotlin --gen-onefile -I $$src_dir -o $(RULEDIR) $$src\",",
            schema.label
        )
        .expect("writing to String should not fail");
        writeln!(output, ")").expect("writing to String should not fail");
        output.push('\n');
        generated_labels.push(format!(":{genrule_name}"));
    }

    writeln!(output, "filegroup(").expect("writing to String should not fail");
    writeln!(output, "    name = \"{name}\",").expect("writing to String should not fail");
    writeln!(output, "    srcs = [").expect("writing to String should not fail");
    for label in generated_labels {
        writeln!(output, "        \"{label}\",").expect("writing to String should not fail");
    }
    writeln!(output, "    ],").expect("writing to String should not fail");
    writeln!(output, ")").expect("writing to String should not fail");
}

fn flatbuffer_outputs(sources: &[SchemaSource], extension: &str) -> Vec<String> {
    sources
        .iter()
        .map(|schema| format!("{}_generated.{extension}", schema.stem))
        .collect()
}

fn render_rust_library(output: &mut String, target_prefix: &str, source_target: &str) {
    writeln!(output, "rust_library(").expect("writing to String should not fail");
    writeln!(output, "    name = \"{target_prefix}_rust_flatbuffers\",")
        .expect("writing to String should not fail");
    writeln!(output, "    srcs = [").expect("writing to String should not fail");
    writeln!(output, "        \"lib.rs\",").expect("writing to String should not fail");
    writeln!(output, "        \":{source_target}\",").expect("writing to String should not fail");
    writeln!(output, "    ],").expect("writing to String should not fail");
    writeln!(output, "    crate_name = \"{target_prefix}_flatbuffers\",")
        .expect("writing to String should not fail");
    writeln!(output, "    crate_root = \"lib.rs\",").expect("writing to String should not fail");
    writeln!(output, "    edition = \"2024\",").expect("writing to String should not fail");
    writeln!(output, "    deps = [\"@crates//:flatbuffers\"],")
        .expect("writing to String should not fail");
    writeln!(output, ")").expect("writing to String should not fail");
}

fn render_swift_library(output: &mut String, target_prefix: &str, source_target: &str) {
    let module_name = upper_camel_case(target_prefix);
    writeln!(output, "swift_library(").expect("writing to String should not fail");
    writeln!(output, "    name = \"{target_prefix}_swift_flatbuffers\",")
        .expect("writing to String should not fail");
    writeln!(output, "    srcs = [").expect("writing to String should not fail");
    writeln!(output, "        \":{source_target}\",").expect("writing to String should not fail");
    for src in FLATBUFFERS_SWIFT_RUNTIME_SRCS {
        writeln!(output, "        \"{src}\",").expect("writing to String should not fail");
    }
    writeln!(output, "    ],").expect("writing to String should not fail");
    writeln!(output, "    module_name = \"{module_name}Flatbuffers\",")
        .expect("writing to String should not fail");
    writeln!(output, ")").expect("writing to String should not fail");
}

fn render_java_runtime_library(output: &mut String) {
    writeln!(output, "java_library(").expect("writing to String should not fail");
    writeln!(output, "    name = \"flatbuffers_java_runtime\",")
        .expect("writing to String should not fail");
    writeln!(output, "    srcs = [").expect("writing to String should not fail");
    for src in FLATBUFFERS_JAVA_RUNTIME_SRCS {
        writeln!(output, "        \"{src}\",").expect("writing to String should not fail");
    }
    writeln!(output, "    ],").expect("writing to String should not fail");
    writeln!(output, "    visibility = [\"//visibility:private\"],")
        .expect("writing to String should not fail");
    writeln!(output, ")").expect("writing to String should not fail");
}

fn render_kotlin_library(output: &mut String, target_prefix: &str, source_target: &str) {
    writeln!(output, "kt_jvm_library(").expect("writing to String should not fail");
    writeln!(output, "    name = \"{target_prefix}_kotlin_flatbuffers\",")
        .expect("writing to String should not fail");
    writeln!(output, "    srcs = [").expect("writing to String should not fail");
    writeln!(output, "        \":{source_target}\",").expect("writing to String should not fail");
    writeln!(output, "    ],").expect("writing to String should not fail");
    writeln!(output, "    deps = [\":flatbuffers_java_runtime\"],")
        .expect("writing to String should not fail");
    writeln!(output, ")").expect("writing to String should not fail");
}

fn bazel_file_label(target_label: &str, repo_relative_path: &Utf8Path) -> AtomResult<String> {
    let package = target_label
        .strip_prefix("//")
        .and_then(|value| value.split_once(':').map(|(package, _)| package))
        .ok_or_else(|| {
            AtomError::new(
                AtomErrorCode::CngTemplateError,
                format!("unsupported module target label for schema generation: {target_label}"),
            )
        })?;
    let prefix = if package.is_empty() {
        String::new()
    } else {
        format!("{package}/")
    };
    let relative = repo_relative_path
        .as_str()
        .strip_prefix(&prefix)
        .ok_or_else(|| {
            AtomError::with_path(
                AtomErrorCode::CngTemplateError,
                "module schema file must live under the module's Bazel package",
                repo_relative_path.as_str(),
            )
        })?;
    Ok(format!("//{package}:{relative}"))
}

fn parse_flatbuffer_namespace(path: &Utf8Path) -> AtomResult<Vec<String>> {
    let contents = fs::read_to_string(path).map_err(|error| {
        AtomError::with_path(
            AtomErrorCode::CngTemplateError,
            format!("failed to read FlatBuffers schema: {error}"),
            path.as_str(),
        )
    })?;
    for line in contents.lines() {
        let trimmed = line.trim();
        if let Some(namespace) = trimmed
            .strip_prefix("namespace ")
            .and_then(|value| value.strip_suffix(';'))
        {
            return Ok(namespace
                .split('.')
                .filter(|segment| !segment.is_empty())
                .map(ToOwned::to_owned)
                .collect());
        }
    }
    Ok(Vec::new())
}

fn kotlin_onefile_output(namespace: &[String], stem: &str) -> Utf8PathBuf {
    let mut output = Utf8PathBuf::new();
    for segment in namespace {
        output.push(segment);
    }
    output.push(format!("{stem}.kt"));
    output
}

fn upper_camel_case(value: &str) -> String {
    value
        .split('_')
        .filter(|segment| !segment.is_empty())
        .map(|segment| {
            let mut chars = segment.chars();
            let mut output = String::new();
            if let Some(first) = chars.next() {
                output.push(first.to_ascii_uppercase());
            }
            output.extend(chars);
            output
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use std::fs;

    use atom_modules::testing::{fixture_resolved_module, fixture_schema_module};
    use camino::Utf8PathBuf;
    use tempfile::tempdir;

    use super::plan_module_flatbuffers;

    #[test]
    fn plans_rust_module_generated_schema_and_build_package() {
        let directory = tempdir().expect("tempdir");
        let root = Utf8PathBuf::from_path_buf(directory.path().to_path_buf()).expect("utf8 path");
        fs::create_dir_all(root.join("modules/fixture/src")).expect("src dir");
        fs::write(
            root.join("modules/fixture/src/lib.rs"),
            r#"
#[atom_macros::atom_record]
struct DeviceInfo {
    model: String,
}
"#,
        )
        .expect("source");

        let module = fixture_resolved_module(&root);
        let package = plan_module_flatbuffers(&root, &module).expect("package");

        assert_eq!(
            package
                .generated_schema
                .as_ref()
                .map(|schema| schema.path.clone()),
            Some(Utf8PathBuf::from(
                "generated/flatbuffers/fixture_module/fixture_module.fbs"
            ))
        );
        assert!(
            package
                .build_contents()
                .contains("@flatbuffers//swift:Sources/FlatBuffers/ByteBuffer.swift")
        );
        assert!(package.build_contents().contains("kt_jvm_library("));
        assert!(
            package
                .rust_wrapper_contents()
                .contains("fixture_module_generated")
        );
    }

    #[test]
    fn plans_native_module_against_existing_schema_labels() {
        let directory = tempdir().expect("tempdir");
        let root = Utf8PathBuf::from_path_buf(directory.path().to_path_buf()).expect("utf8 path");
        fs::create_dir_all(root.join("modules/schema")).expect("schema dir");
        fs::write(
            root.join("modules/schema/fixture.fbs"),
            "namespace atom.native_fixture;\n",
        )
        .expect("schema");

        let module = fixture_schema_module(&root, "modules/schema/fixture.fbs");
        let package = plan_module_flatbuffers(&root, &module).expect("package");

        assert!(package.generated_schema.is_none());
        assert_eq!(
            package.source_schemas[0].label,
            "//modules/schema:fixture.fbs"
        );
        assert_eq!(
            package.source_schemas[0].kotlin_out,
            Utf8PathBuf::from("atom/native_fixture/fixture.kt")
        );
    }
}
