#!/usr/bin/env bash
set -euo pipefail

# Sets up BuildBuddy remote cache for local development.
# Usage: scripts/setup-buildbuddy.sh <api-key>
#    or: BUILDBUDDY_API_KEY=<key> scripts/setup-buildbuddy.sh
#
# This writes user.bazelrc (gitignored) with the API key and enables
# the buildbuddy config for all builds.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
USER_BAZELRC="$REPO_ROOT/user.bazelrc"

API_KEY="${1:-${BUILDBUDDY_API_KEY:-}}"

if [[ -z "$API_KEY" ]]; then
  echo "Error: No API key provided."
  echo "Usage: $0 <api-key>"
  echo "   or: BUILDBUDDY_API_KEY=<key> $0"
  exit 1
fi

cat > "$USER_BAZELRC" <<EOF
# Auto-generated by scripts/setup-buildbuddy.sh — do not commit
build --config=buildbuddy
build --remote_header=x-buildbuddy-api-key=${API_KEY}
EOF

echo "Wrote $USER_BAZELRC — BuildBuddy remote cache enabled."
